{% set version = "0.5.0" %}

package:
  name: teensytoany
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/teensytoany/teensytoany-{{ version }}.tar.gz
  sha256: 066589b3c2a1ebc83f3babe9d9175533e02a0654c5318fcec6cfda55c549ab4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<4
    - pip
  run:
    - python >=3.9,<4
    - pyserial
    - packaging

test:
  imports:
    - teensytoany

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
