{% set version = "0.7.0" %}

package:
  name: teensytoany
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/teensytoany/teensytoany-{{ version }}.tar.gz
  sha256: 8b3091f8bd5fd97039d1136117c64d15182423955d4f3391007d4a32109b02db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyserial
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - teensytoany

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
