{% set version = "0.13.0" %}

package:
  name: teensytoany
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/teensytoany/teensytoany-{{ version }}.tar.gz
  sha256: ebf396be4edb5d38c535419a08870883c5db65e8238f20f0d164444dda3b4eeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - teensytoany_programmer = teensytoany.programmer:teensytoany_programmer
    - teensytoany_i2c_scan = teensytoany.i2c_scan:main
    - teensytoany_list = teensytoany.list:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyserial
    - packaging

test:
  requires:
    - python {{ python_min }}
    - pip
    # click needed to command line utilities but not needed for library
    - click
  imports:
    - teensytoany
  commands:
    - pip check
    - teensytoany_programmer --help
    - teensytoany_i2c_scan --help
    - teensytoany_list --help

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
