{% set version = "0.9.0" %}

package:
  name: teensytoany
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/teensytoany/teensytoany-{{ version }}.tar.gz
  sha256: fe0ae63e75aebd708b58fb0246c8b60b973cd9cebaa5613711a9ac260f4b61b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyserial
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - teensytoany

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
