{% set version = "0.4.0" %}

package:
  name: teensytoany
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/teensytoany/teensytoany-{{ version }}.tar.gz
  sha256: 07e3c0b287525a2ed5c1829125c04d8ac7e5bc8006560e72e0f7ce64467ebacb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<4
    - pip
  run:
    - python >=3.9,<4
    - pyserial
    - packaging

test:
  imports:
    - teensytoany

about:
  home: https://github.com/ramonaoptics/python-teensytoany/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pythonic way to control the TeensyToAny debugging board

extra:
  recipe-maintainers:
    - hmaarrfk
